//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTravel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebTravelEntities : DbContext
    {
        public WebTravelEntities()
            : base("name=WebTravelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_blog_tra> tbl_blog_tra { get; set; }
        public DbSet<tblSysPicture> tblSysPictures { get; set; }
        public DbSet<web_vangia_config> web_vangia_config { get; set; }
        public DbSet<web_vangia_doitac> web_vangia_doitac { get; set; }
        public DbSet<web_vangia_duanmau> web_vangia_duanmau { get; set; }
        public DbSet<web_vangia_employee> web_vangia_employee { get; set; }
        public DbSet<web_vangia_language> web_vangia_language { get; set; }
        public DbSet<web_vangia_menu> web_vangia_menu { get; set; }
        public DbSet<web_vangia_menucon> web_vangia_menucon { get; set; }
        public DbSet<web_vangia_news> web_vangia_news { get; set; }
        public DbSet<web_vangia_products> web_vangia_products { get; set; }
        public DbSet<web_vangia_project> web_vangia_project { get; set; }
        public DbSet<web_vangia_silde> web_vangia_silde { get; set; }
        public DbSet<web_vangia_team> web_vangia_team { get; set; }
        public DbSet<web_vangia_tuyendung> web_vangia_tuyendung { get; set; }
        public DbSet<web_vangia_type_products> web_vangia_type_products { get; set; }
        public DbSet<web_vangia_typeproject> web_vangia_typeproject { get; set; }
    }
}
