//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_menu
    {
        public int vangia_id_menu { get; set; }
        public string vangia_name_menu { get; set; }
        public string vangia_link_menu { get; set; }
        public Nullable<int> vangia_status_menu { get; set; }
        public Nullable<int> vangia_order_menu { get; set; }
        public Nullable<int> vangia_id_language { get; set; }
        public string vangia_key_menu { get; set; }
        public Nullable<int> vangia_loai_menu { get; set; }
        public string vangia_tt_menu { get; set; }
    }
}
