//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_news
    {
        public int vangia_id_news { get; set; }
        public string vangia_name_news { get; set; }
        public string vangia_img_news { get; set; }
        public string vangia_links_news { get; set; }
        public Nullable<int> vangia_type_news { get; set; }
        public string vangia_img1_news { get; set; }
        public string vangia_img2_news { get; set; }
        public string vangia_tomtat_news { get; set; }
        public string vangia_noidung_news { get; set; }
        public Nullable<int> vangia_status_news { get; set; }
        public Nullable<int> vangia_order_news { get; set; }
        public Nullable<int> vangia_language_news { get; set; }
        public string vangia_vanban_news { get; set; }
    }
}
