//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_doitac
    {
        public int vangia_id_doitac { get; set; }
        public string vangia_name_doitac { get; set; }
        public string vangia_img_doitac { get; set; }
        public string vangia_noidung { get; set; }
        public Nullable<int> vangia_status_doitac { get; set; }
        public Nullable<int> vangia_order_doitac { get; set; }
        public Nullable<int> vangia_language_doitac { get; set; }
        public Nullable<int> vangia_type_doitac { get; set; }
    }
}
