//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_employee
    {
        public int vangia_id_employee { get; set; }
        public string vangia_img_employee { get; set; }
        public string vangia_name_employee { get; set; }
        public string vangia_tiesu_employee { get; set; }
        public Nullable<int> vangia_status_employee { get; set; }
        public Nullable<int> vangia_order_employee { get; set; }
        public Nullable<int> vangia_language_employee { get; set; }
        public Nullable<int> vangia_team_employee { get; set; }
        public string vangia_noidung_employee { get; set; }
    }
}
