//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_team
    {
        public int vangia_id_team { get; set; }
        public string vangia_name_team { get; set; }
        public Nullable<int> vangia_status_team { get; set; }
        public Nullable<int> vangia_language_team { get; set; }
        public string vangia_tomtat_team { get; set; }
        public string vangia_img_team { get; set; }
    }
}
