//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_tuyendung
    {
        public int vangia_id_tuyendung { get; set; }
        public string vangia_name_tuyendung { get; set; }
        public string vangia_img_tuyendung { get; set; }
        public string vangia_tomtat_tuyendung { get; set; }
        public string vangia_img1_tuyendung { get; set; }
        public string vangia_img2_tuyendung { get; set; }
        public Nullable<int> vangia_status_tuyendung { get; set; }
        public string vangia_noidung_tuyendung { get; set; }
        public Nullable<int> vangia_language_tuyendung { get; set; }
        public Nullable<int> vangia_order_tuyendung { get; set; }
        public Nullable<int> vangia_type_tuyendung { get; set; }
        public string vangia_ma_tuyendung { get; set; }
        public string vangia_vitri_tuyendung { get; set; }
        public string vangia_soluong_tuyendung { get; set; }
        public string vangia_diadiem_tuyendung { get; set; }
        public string vangia_date_tuyendung { get; set; }
    }
}
