//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_duanmau
    {
        public int vangia_id_duanmau { get; set; }
        public string vangia_img_duanmau { get; set; }
        public string vangia_name_duanmau { get; set; }
        public string vangia_time_duanmau { get; set; }
        public string vangia_img1_duanmau { get; set; }
        public string vangia_img2_duanmau { get; set; }
        public string vangia_img3_duanmau { get; set; }
        public Nullable<int> vangia_status_duanmau { get; set; }
        public Nullable<int> vangia_order_duanmau { get; set; }
        public Nullable<int> vangia_language { get; set; }
        public string vangia_content_duanmau { get; set; }
        public string vangia_tomtat_duanmau { get; set; }
    }
}
