//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataAdminVanGiaEntities : DbContext
    {
        public DataAdminVanGiaEntities()
            : base("name=DataAdminVanGiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ctr_in_form> ctr_in_form { get; set; }
        public DbSet<ctr_steel> ctr_steel { get; set; }
        public DbSet<form_steel> form_steel { get; set; }
        public DbSet<form_store> form_store { get; set; }
        public DbSet<form_store_para> form_store_para { get; set; }
        public DbSet<fs_auth> fs_auth { get; set; }
        public DbSet<fs_manga> fs_manga { get; set; }
        public DbSet<fs_manga_chap> fs_manga_chap { get; set; }
        public DbSet<fs_manga_tag> fs_manga_tag { get; set; }
        public DbSet<fs_manga_type> fs_manga_type { get; set; }
        public DbSet<mar_project> mar_project { get; set; }
        public DbSet<pct_department> pct_department { get; set; }
        public DbSet<pct_employee> pct_employee { get; set; }
        public DbSet<pct_ticket> pct_ticket { get; set; }
        public DbSet<pct_title> pct_title { get; set; }
        public DbSet<project_steel> project_steel { get; set; }
        public DbSet<so_orther> so_orther { get; set; }
        public DbSet<so_orther_detail> so_orther_detail { get; set; }
        public DbSet<so_prod_image_detail> so_prod_image_detail { get; set; }
        public DbSet<store_> store_ { get; set; }
        public DbSet<store_cate> store_cate { get; set; }
        public DbSet<store_com_ship> store_com_ship { get; set; }
        public DbSet<store_com_type> store_com_type { get; set; }
        public DbSet<store_company> store_company { get; set; }
        public DbSet<store_contact> store_contact { get; set; }
        public DbSet<store_exp> store_exp { get; set; }
        public DbSet<store_imp> store_imp { get; set; }
        public DbSet<store_prod> store_prod { get; set; }
        public DbSet<store_prod_sku> store_prod_sku { get; set; }
        public DbSet<store_slot> store_slot { get; set; }
        public DbSet<store_stock> store_stock { get; set; }
        public DbSet<store_unit> store_unit { get; set; }
        public DbSet<sys_company> sys_company { get; set; }
        public DbSet<sys_fs_help> sys_fs_help { get; set; }
        public DbSet<sys_gridview_control> sys_gridview_control { get; set; }
        public DbSet<sys_group_page> sys_group_page { get; set; }
        public DbSet<sys_info> sys_info { get; set; }
        public DbSet<sys_mapped_col> sys_mapped_col { get; set; }
        public DbSet<sys_mapped_join> sys_mapped_join { get; set; }
        public DbSet<sys_mapped_operators> sys_mapped_operators { get; set; }
        public DbSet<sys_mapped_table> sys_mapped_table { get; set; }
        public DbSet<sys_mapped_ty_op> sys_mapped_ty_op { get; set; }
        public DbSet<sys_mapped_type> sys_mapped_type { get; set; }
        public DbSet<sys_page> sys_page { get; set; }
        public DbSet<tbl_blog_tra> tbl_blog_tra { get; set; }
        public DbSet<tbl_menu_dulich> tbl_menu_dulich { get; set; }
        public DbSet<tbl_new_dulich> tbl_new_dulich { get; set; }
        public DbSet<tbl_products_tra> tbl_products_tra { get; set; }
        public DbSet<tbl_slide_dulich> tbl_slide_dulich { get; set; }
        public DbSet<tbl_slide_tra> tbl_slide_tra { get; set; }
        public DbSet<tbl_spam_dulich> tbl_spam_dulich { get; set; }
        public DbSet<tblDomain> tblDomains { get; set; }
        public DbSet<tblSysCompany> tblSysCompanies { get; set; }
        public DbSet<tblSysGroupPage> tblSysGroupPages { get; set; }
        public DbSet<tblSysGroupPageDetail> tblSysGroupPageDetails { get; set; }
        public DbSet<tblSysPicture> tblSysPictures { get; set; }
        public DbSet<tblSysUser_Page> tblSysUser_Page { get; set; }
        public DbSet<tblSysUserGroupPage> tblSysUserGroupPages { get; set; }
        public DbSet<tblSysUserGroupPageDetail> tblSysUserGroupPageDetails { get; set; }
        public DbSet<tblSysUserGroupPagePage> tblSysUserGroupPagePages { get; set; }
        public DbSet<tblSysUserRoleGroup> tblSysUserRoleGroups { get; set; }
        public DbSet<tblSysUserRolePage> tblSysUserRolePages { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblUserCloud> tblUserClouds { get; set; }
        public DbSet<tblUserFriend> tblUserFriends { get; set; }
        public DbSet<tblUserImg> tblUserImgs { get; set; }
        public DbSet<user_steel> user_steel { get; set; }
        public DbSet<web_banner> web_banner { get; set; }
        public DbSet<web_chater> web_chater { get; set; }
        public DbSet<web_chater_content> web_chater_content { get; set; }
        public DbSet<web_content> web_content { get; set; }
        public DbSet<web_content_other> web_content_other { get; set; }
        public DbSet<web_customer> web_customer { get; set; }
        public DbSet<web_department> web_department { get; set; }
        public DbSet<web_employer> web_employer { get; set; }
        public DbSet<web_list_product> web_list_product { get; set; }
        public DbSet<web_menu_root> web_menu_root { get; set; }
        public DbSet<web_products> web_products { get; set; }
        public DbSet<web_title> web_title { get; set; }
        public DbSet<web_vangia_config> web_vangia_config { get; set; }
        public DbSet<web_vangia_doitac> web_vangia_doitac { get; set; }
        public DbSet<web_vangia_duanmau> web_vangia_duanmau { get; set; }
        public DbSet<web_vangia_employee> web_vangia_employee { get; set; }
        public DbSet<web_vangia_language> web_vangia_language { get; set; }
        public DbSet<web_vangia_menu> web_vangia_menu { get; set; }
        public DbSet<web_vangia_menucon> web_vangia_menucon { get; set; }
        public DbSet<web_vangia_news> web_vangia_news { get; set; }
        public DbSet<web_vangia_products> web_vangia_products { get; set; }
        public DbSet<web_vangia_project> web_vangia_project { get; set; }
        public DbSet<web_vangia_silde> web_vangia_silde { get; set; }
        public DbSet<web_vangia_team> web_vangia_team { get; set; }
        public DbSet<web_vangia_tuyendung> web_vangia_tuyendung { get; set; }
        public DbSet<web_vangia_type_products> web_vangia_type_products { get; set; }
        public DbSet<web_vangia_typeproject> web_vangia_typeproject { get; set; }
        public DbSet<fs_manga_img> fs_manga_img { get; set; }
        public DbSet<grid_view_mapping> grid_view_mapping { get; set; }
        public DbSet<log_store_prod> log_store_prod { get; set; }
        public DbSet<sys_data_fixed> sys_data_fixed { get; set; }
        public DbSet<sys_store_prod> sys_store_prod { get; set; }
        public DbSet<tblSysUserListShareDetail> tblSysUserListShareDetails { get; set; }
        public DbSet<tblSysUserRoleRecord> tblSysUserRoleRecords { get; set; }
        public DbSet<wb_advertising> wb_advertising { get; set; }
        public DbSet<wb_banner> wb_banner { get; set; }
        public DbSet<wb_comment> wb_comment { get; set; }
        public DbSet<wb_mail> wb_mail { get; set; }
        public DbSet<wb_menu> wb_menu { get; set; }
        public DbSet<wb_menu_products> wb_menu_products { get; set; }
        public DbSet<wb_products> wb_products { get; set; }
        public DbSet<web_tr_menu_product> web_tr_menu_product { get; set; }
        public DbSet<web_tr_menutop> web_tr_menutop { get; set; }
        public DbSet<web_tr_products> web_tr_products { get; set; }
        public DbSet<web_tr_quangcao> web_tr_quangcao { get; set; }
    }
}
