//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_slide_dulich
    {
        public int id_slide_dulich { get; set; }
        public string name_silde_dulich { get; set; }
        public string img_silde_dulich { get; set; }
        public string tomtat_silde_dulich { get; set; }
        public Nullable<int> trangthai_silde_dulich { get; set; }
        public Nullable<int> thutu_silde_dulich { get; set; }
        public Nullable<int> thutunew_dulich { get; set; }
    }
}
