//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_new_dulich
    {
        public int id_new_dulich { get; set; }
        public string name_new_dulich { get; set; }
        public string img_new_dulich { get; set; }
        public Nullable<int> thutu_new_dulich { get; set; }
        public string tomtat_new_dulich { get; set; }
        public string img1_new_dulich { get; set; }
        public string img2_new_dulich { get; set; }
        public string img3_new_dulich { get; set; }
        public string img4_new_dulich { get; set; }
        public string img5_new_dulich { get; set; }
        public string mota_new_dulich { get; set; }
        public Nullable<int> trangthai_new_dulich { get; set; }
        public Nullable<int> type_new_dulich { get; set; }
        public string img6_new_dulich { get; set; }
        public string img7_new_dulich { get; set; }
        public string class_new_dulich { get; set; }
    }
}
