//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_menu_dulich
    {
        public int id_menu_dulich { get; set; }
        public string name_menu_dulich { get; set; }
        public string link_menu_dulich { get; set; }
        public Nullable<int> trangthai_menu_dulich { get; set; }
        public Nullable<int> thutu_menu_dulich { get; set; }
    }
}
