//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDomain
    {
        public int id { get; set; }
        public string domain_name { get; set; }
        public Nullable<long> id_company { get; set; }
        public Nullable<int> domain_status { get; set; }
    }
}
