//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysUserListShareDetail
    {
        public long group_role_id { get; set; }
        public long user_id { get; set; }
        public Nullable<int> id_company { get; set; }
    }
}
