//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysGroupPageDetail
    {
        public int id_page { get; set; }
        public int id_group_page { get; set; }
        public string page_name { get; set; }
        public int page_status { get; set; }
        public Nullable<System.DateTime> page_create { get; set; }
        public string page_link { get; set; }
        public int id_company { get; set; }
        public string page_key { get; set; }
        public Nullable<int> max_record { get; set; }
        public Nullable<int> page_order { get; set; }
        public int page_type_role { get; set; }
        public string page_icon { get; set; }
        public Nullable<int> page_type { get; set; }
        public Nullable<int> page_type_chart { get; set; }
    }
}
