//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysUser_Page
    {
        public int id_user_page { get; set; }
        public string user_page_name { get; set; }
        public string user_page_control { get; set; }
        public string user_page_sexy { get; set; }
        public Nullable<int> user_page_parent { get; set; }
        public Nullable<int> user_page_order { get; set; }
        public Nullable<int> user_vip { get; set; }
    }
}
