//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_project
    {
        public int vangia_id_project { get; set; }
        public string vangia_img1_project { get; set; }
        public string vangia_img2_project { get; set; }
        public string vangia_img3_project { get; set; }
        public string vangia_img_project { get; set; }
        public string vangia_content_project { get; set; }
        public string vangia_name_project { get; set; }
        public string vangia_time_project { get; set; }
        public Nullable<int> vangia_status_project { get; set; }
        public Nullable<int> vangia_order_project { get; set; }
        public Nullable<int> vangia_language_project { get; set; }
        public string vangia_tomtat_project { get; set; }
        public Nullable<int> vangia_typeid_project { get; set; }
    }
}
