//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_language
    {
        public int vangia_id_language { get; set; }
        public string vangia_name_language { get; set; }
        public string vangia_code_langue { get; set; }
        public Nullable<int> vangia_status_lague { get; set; }
        public string vangia_icon_language { get; set; }
    }
}
