//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_silde
    {
        public int vangia_id_silde { get; set; }
        public string vangia_noidung_silde { get; set; }
        public string vangia_tomtat_silde { get; set; }
        public string vangia_img_silde { get; set; }
        public string vangia_name_silde { get; set; }
        public Nullable<int> vangia_status_silde { get; set; }
        public Nullable<int> vangia_order_silde { get; set; }
        public Nullable<int> vangia_language_silde { get; set; }
        public string vangia_link_silde { get; set; }
        public string vangia_stype_slide { get; set; }
        public Nullable<int> vangia_type_slide { get; set; }
        public Nullable<int> company { get; set; }
    }
}
