//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_products
    {
        public int vangia_id_products { get; set; }
        public string vangia_img_products { get; set; }
        public string vangia_name_products { get; set; }
        public string vangia_noidung_products { get; set; }
        public string vangia_img1_products { get; set; }
        public string vangia_img2_products { get; set; }
        public string vangia_img3_products { get; set; }
        public string vangia_tomtat_products { get; set; }
        public Nullable<int> vangia_order_products { get; set; }
        public Nullable<int> vangia_language_products { get; set; }
        public Nullable<int> vangia_status_products { get; set; }
        public Nullable<int> vangia_type_products { get; set; }
        public string ful_img4_products_vg { get; set; }
        public string ful_img5_products_vg { get; set; }
        public string ful_img6_products_vg { get; set; }
        public string ful_img7_products_vg { get; set; }
        public string ful_img8_products_vg { get; set; }
        public string ful_img9_products_vg { get; set; }
    }
}
