//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_type_products
    {
        public int vangia_id_type_products { get; set; }
        public string vangia_img_type_products { get; set; }
        public string vangia_name_type_products { get; set; }
        public Nullable<int> vangia_status_type_products { get; set; }
        public Nullable<int> vangia_order_type_products { get; set; }
        public Nullable<int> vangia_language_type_products { get; set; }
    }
}
