//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_menucon
    {
        public int vangia_id_menucon { get; set; }
        public string vangia_name_menucon { get; set; }
        public string vangia_link_menucon { get; set; }
        public string vangia_menucha_menucon { get; set; }
        public Nullable<int> vangia_status_menucon { get; set; }
        public Nullable<int> vangia_order_menucon { get; set; }
        public Nullable<int> vangia_language_menucon { get; set; }
    }
}
