//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVanGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_config
    {
        public int id { get; set; }
        public string name_vg { get; set; }
        public string key_word_vg { get; set; }
        public Nullable<int> laguage_word_vg { get; set; }
        public Nullable<int> order_word_vg { get; set; }
    }
}
